default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PG_USERNAME") { "your_db_user" } %>
  password: <%= ENV.fetch("PG_PASSWORD") { "your_db_password" } %>
  host: <%= ENV.fetch("PG_HOST") { "localhost" } %>
  port: <%= ENV.fetch("PG_PORT") { 5432 } %>

development:
  <<: *default
  database: your_app_development

test:
  <<: *default
  database: your_app_test

production:
  primary:
    <<: *default
    database: your_app_production
    # SSL or connection pooling settings can go here

  cache:
    <<: *default
    database: your_app_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: your_app_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: your_app_production_cable
    migrations_paths: db/cable_migrate
